[project]
src = "src"
out = "out"
dot_env = ".env"
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["snekmate"]

[networks.pyevm]
is_zksync = false

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337

[networks.sepolia]
url = "https://ethereum-sepolia-rpc.publicnode.com"
chain_id = 11155111

[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true

[networks.zksync.contracts]
eth_usd_price_feed = { address = "0xfEefF7c3fB57d18C5C6Cdd71e45D2D0b4F9377bF" }
btc_usd_price_feed = { address = "0x95Bc57e794aeb02E4a16eff406147f3ce2531F83" }
weth = { address = "0xf00DAD97284D0c6F06dc4Db3c32454D4292c6813" }
wbtc = { address = "0xBBeB516fb02a01611cBBE0453Fe3c580D7281011" }

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
